baseURL: http://docs.hofstadter.io/
languageCode: en-us
DefaultContentLanguage: en
title: Hofstadter Documentation
enableGitInfo: true
pygmentsCodeFences: true
pygmentsStyle: github
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: false
params:
  ordersectionsby: weight
  disableSearch: false
  disableReadmoreNav: false
  highlightClientSide: false
  menushortcutsnewtab: true
  ga: G-06EV4G0M20
  github_project_repo: https://github.com/hofstadter-io/hof
  github_repo: https://github.com/hofstadter-io/hof
  time_format_default: January 2, 2006
  hofver: v0.6.8-rc.2
  cuever: v0.5.0
  cuedocBase: https://pkg.go.dev/cuelang.org/go@v0.5.0
  slackLink: https://join.slack.com/t/hofstadter-io/shared_invite/zt-e5f90lmq-u695eJur0zE~AG~njNlT1A
  keywords:
    - hof
    - hofstadter
    - documentation
    - docs
  beta: |-
    The `hof gen` ad-hoc feature (`-T`) is only available in the next beta.

    ```
    go install github.com/hofstadter-io/hof/cmd/hof@v0.6.8-rc.2
    ```

    [Download binaries on GitHub](https://github.com/hofstadter-io/hof/releases/tag/v0.6.8-rc.2)
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 3
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
menu:
  shortcuts:
    - name: <i class='fab fa-github'></i> GitHub
      url: https://github.com/hofstadter-io/hof
      weight: 1
    - name: <i class='fas fa-comments'></i> Slack
      url: https://join.slack.com/t/hofstadter-io/shared_invite/zt-e5f90lmq-u695eJur0zE~AG~njNlT1A
      weight: 2
    - name: <i class='fas fa-home'></i> hof.io
      url: https://hofstadter.io
      weight: 3
